### ISSUE TITLE
Hotkey still works when app is turned off

### ISSUE THREAD

**Issue by lukors** [bytepixie/snippetpixie#100]
**Describe the bug**
Running `snippetpixie --stop` in terminal does not disable the hotkey.

**To Reproduce**
Steps to reproduce the behaviour:
1. run `snippetpixie --stop` in the terminal
2. Press the hotkey (`` ctrl ` `` by default)

**Expected behaviour**
Since Snippetpixie isn't running, nothing should happen.

**Desktop**
 - OS: Pop!_OS 21.04
 - Snippet Pixie Version 1.5.3

**Additional context**
Being able to turn off the application is nicer than having to think of a hotkey that is not used in any of the many hotkey-heavy applications on my computer.

**Comment by ianmjones** [comment]
I don't think this is something that can be done, it's kind of against the nature of a global hotkey.

When you use `snippetpixie --stop` you're just turning temporarily off the automatic expansion of snippets. That can be achieved permanently via the menu option, although there's no command line option for toggling that yet.

The global hotkey is set at the system level and simply asks the operating system to call `snippetpixie search-and-paste` when the hotkey is used. The only way to disable it via Snippet Pixie is to remove the currently set hotkey from the menu option.

Otherwise, you can remove it from the OS level through whatever means it provides.

Instead, I would recommend trying to find a hotkey that you can safely use across applications. I realise that can be difficult, even I recently bumped into existing use of the default Ctrl+\` by another app, and had to switch to Super+\` for Snippet Pixie.
