### ISSUE TITLE
Not working in firefox, code, libreoffice. Supported software list?

### ISSUE THREAD

**Issue by henricazottes** [bytepixie/snippetpixie#26]
**Describe the bug**
Snippet is not expanded.

**To Reproduce**
Open SP
Enter snippet shortcut: cct`
Enter snippet: coucou toi
Open an app with a text area, type the shortcut (tested on firefox, elementary code editor, libreoffice).

**Expected behaviour**
Snippet should expand.

**Desktop (please complete the following information):**
 - OS: elementary OS 5.0 Juno
 - Snippet Pixie Version 1.0
 - Related Application Firefox, Code, LireOffice

**Additional context**
I thought SP wasn't working at all cause I tried on those 3 software without any result before trying it in the app drawer of elementary (where it finally did work). Is there any list of supported software?

**Comment by ianmjones** [comment]
Thanks for the bug report @henricazottes.

We don't have a list of supported software yet as it's early days and we need people to report their findings. However, we'd probably list things more generally based on their technology rather than individual applications.

It doesn't look like Libre Office is properly accessible, so it does not work.

I've tested with Code, not had any problems there.

I use Firefox as my primary web browser and have very little problem there too, there are occasional websites that muck about enough with textareas and inputs to break expansion, but most work for me.

Could you try the following for me to see why Code has issues for you.

1. Open Terminal and run `com.github.bytepixie.snippetpixie --stop`
1. Then run `G_MESSAGES_DEBUG=all com.github.bytepixie.snippetpixie --start`
1. Switch to Code and try and expand your snippet.
1. Switch back to Terminal and hit `Ctrl-c` to stop Snippet Pixie.

Please then copy and post the Terminal output here, thanks.

**Comment by ianmjones** [comment]
More info not supplied, closing.

If anyone has more information, in particular debug output when having problems with Code, please post and I'll re-open the issue.
