### ISSUE TITLE
Typing problems in Ubuntu Focal Fossa

### ISSUE THREAD

**Issue by corlaez** [bytepixie/snippetpixie#62]
**Describe the bug**
When this app is running text input suffers huge slow downs making it impossible to use.
Firefox text input works fine, it makes sense since this app is not trying to replace snippets there.

**To Reproduce**
Steps to reproduce the behaviour:
1. On a Ubuntu Focal Fossa open Ubuntu Software
2. Install SnippetPixie
3. Create snippets and try to use them in your code editor
4. See how slow the typing experience is

**Expected behaviour**
This app should not slow down your typing, the experience should match the smooth experience in elementaryOS

**Desktop (please complete the following information):**
 - OS Ubuntu 20.04 Focal Fossa
 - Snippet Pixie Version 1.3.1
 - Related Application Non specific to an app. I saw it in Visual studio code and a browser text input

**Comment by ianmjones** [comment]
Hey @corlaez, thanks for the bug report, much appreciated.

Please can you do me a favour and do a quick typing test in the default "Text Editor" that comes installed with Ubuntu 20.04? How does that compare to VS Code?

Have you rebooted since installing Snippet Pixie? If not, please could you do that for me and then do another couple of speed checks, including in "Text Editor" again, any improvements?

**Comment by corlaez** [comment]
Hey @ianmjones, I have updates.

*Before restart, step by step*
1. I reinstalled the software and set a simple snippet: `;y` mapping to `ooo`
* Reproduced the terrible typing lag in Text Editor as in VScode and brave browser inputs.
* The lag is *only* triggered whenever I type the 'y'. 
* Moreover I found a related error. I can actually see the editor trying to select the previous letter to `y` (I guess to check if the rest is actually `;`) and if I keep typing when it's selecting I override the selected text.
2. I changed the snippet to: `qwerty` mapping to `ooo`
* Reproduced the terrible typing lag in Text Editor as in VScode and brave browser inputs.
* The lag is *only* triggered whenever I type the 'y'. It is clear that the problem arises when I type the last letter of the snippet, regardless of how short or long it is.
* Moreover I found a related error. I can actually see the editor trying to select the previous letter to `y` (I guess to check if the rest is actually `qwert`) and if I keep typing when it's selecting I override the selected text.

**Comment by corlaez** [comment]
*After restart*
1. Typing works normal (snippetPixie is not on)
2. Start snippetPixie
3. All described problems returned
4. Snippet Pixie Hangs, a dialog to force quit pops up. (In retrospective this happened once or maybe twice while writting the "Before restart" comment)
5. This time I did not quit the app, as I was trying to write the dialog title
6. All hell got loose. The typing got terribly, unmeasurably slow. Now every keystroke was a huge problem. Snippet Pixie was impossible to close, I couldn't even htop... hard reset

I hope this helps find the problem.

**Comment by ianmjones** [comment]
Thanks for running those tests @corlaez and taking the time to fully document, very helpful.

> I reinstalled the software

Thank you, saves me asking you to do that! 😄 

> I can actually see the editor trying to select the previous letter to y (I guess to check if the rest is actually qwert) and if I keep typing when it's selecting I override the selected text.

There are two ways that Snippet Pixie can check whether an abbreviation has just been entered...

### Gtk/Atk
In apps built with the Gtk library and the "Accessibility Toolkit" Atk, such as "Text Editor", Snippet Pixie can just ask the input control for the text that was entered at specific positions in the control, if it finds a matched abbreviation it'll tell the control to replace the abbreviation with the expanded text. This is fast, and pretty accurate.

### Text Selection
In apps that do not use the Gtk library for their input, such as VS Code, Snippet Pixie can't ask the app for the text that was entered before a recognised trigger key (`y` in this case). So instead Snippet Pixie has to fake keyboard input as if you were selecting the previous text, checks what characters are selected to make sure an abbreviation has been entered, and then replaces the selected abbreviation text with expanded text if there's a match by faking a paste. If no match, it just cancels the selection.

This text selection and checking is a relatively slow process, especially compared to the Gtk method. When using the text selection method you can sometimes see the selection happen, and because the selection checking is prone to errors (I won't go into why, but threads, ugh), Snippet Pixie sometimes has another try or two to check for an abbreviation if things go wrong.

I created a fresh Ubuntu 20.04 VM (qemu) and followed your steps for installing and testing etc, it worked fast in Text Editor and ok in VS Code (the occasional failure to expand). I definitely need to see if I can speed up and fine-tune the text selection method.

1. It sounds like it's especially slow for you, but worryingly, am I right in thinking you're seeing the whole text selection process happening on Text Editor, when it shouldn't be?

2. Would you mind letting me know the CPUs and RAM your installation are using?

**Comment by corlaez** [comment]
1. While on Text Editor I don't see any visual indication of selection if I type quickly I will override the text when I type the last letter of a snippet (and I can end up deleting as many characters as the snippet pattern has). That's why I bundled the behavior with vscode and brave. I think that brave inputs is the worst, then vscode and then text editor. However they are all very slow as this is not just "slow to expand" but slow to type in general as this problems arise if I type the last letter of any snippet pattern I have.

2. **Specifications:**
OS: Ubuntu 20.04 LTS x86_64 
Host: Aspire A515-43 V1.05 
Kernel: 5.4.0-26-generic 
CPU: AMD Ryzen 3 3200U with Radeon Vega Mobile Gfx (4) @ 2.600GHz 
GPU: AMD ATI 05:00.0 Picasso
Memory: 2962MiB / 13997MiB

**Comment by ianmjones** [comment]
> Additionally I used snippet pixie with the same machine but using elementaryOS and I didn't have
these issues.

Aha! That could be the key difference, on elementary you're using a "normal" installed binary (assuming you installed via AppCenter), on Ubuntu you're using a version bundled as a snap.

Still, in my tests I didn't see a massive difference in speed between binary and snap version, maybe a minor reduction in speed with the snap. It's something I should look into though.

And interestingly, while running some tests just now, this happened, a problem with the service that Snippet Pixie relies on for getting notifications of interesting keystrokes...

![Screenshot from 2020-04-24 22-51-26](https://user-images.githubusercontent.com/4710/80260162-26508080-867f-11ea-8bc4-bb3780c389fe.png)

Very curious, might be related to the issues you're seeing too. :shrug: 

Until I can find ways to improve the speed, if I can, I would encourage you to use abbreviations that end with a character you rarely use in normal text. That way Snippet Pixie isn't doing anywhere near the work on normal text, only triggering its abbreviation checking code when you type that trigger key, such as "\`".

Thanks again for the info.

**Comment by corlaez** [comment]
Certainly in elementaryOS I used the AppCenter version, in ubuntu I used the snap.
Thanks for suggesting to use a less common last character, it would certainly help to make the problem more manageable.

**Comment by corlaez** [comment]
I see you are working on a fix already @ianmjones 
I was going to suggest (at least where the selection is expensive) if it was possible to do an early check (especially for longer snippet strings)
Example
Snippet: `1234'`
When `'` is typed instead of trying to select the 5 letters of the matcher string maybe just select the last 2:  `4'`
If the last two letters don't match we don't need to continue. If it matches we would validate the whole string.

I don't know how big the extra cost of an additional check it is but I suspect it could help the experience at least in the slowest platforms (like the brave browser inputs in ubuntu 20.04 snap of snippetPixie)

Just throwing some ideas out there, I have no idea if that's going to work out for the target platforms.

**Comment by ianmjones** [comment]
Hey @corlaez, thanks for the suggestion, but Snippet Pixie already does exactly this!

In fact, part of the work I've done in the PR linked to this here issue fine tunes the algorithm to be more efficient in the chunks it jumps back through the text to find matches, including bailing earlier.

The biggest problem at the moment is threading and the Gtk clipboard subsystem locking up for a period of time when using the text selection method. I've tried all kinds of things, including using alternate methods such as spawning out to `xclip`, but there's various issues with that method too (and I'm not too thrilled about depending on an external tool).

I've spent many hours on this over the last few ~~days~~ nights, getting closer and closer to a solution, well, to something more performant anyway.
