### ISSUE TITLE
Package as Flatpak for elementary OS 6

### ISSUE THREAD

**Issue by danrabbit** [bytepixie/snippetpixie#93]
As you might have heard, AppCenter is going Flatpak! For elementary OS 6, we will not longer be accepting Debian packaging, so your app will need to be updated.

We have documentation on our developer guide for writing your Flatpak manifest here: https://docs.elementary.io/develop/writing-apps/our-first-app/packaging#flatpak-manifest

Also, in case you missed it, elementary OS 6 beta 2 is [now available](https://builds.elementary.io). This is a great time to get your app packaged up as Flatpak and test that everything is working before the final release. AppCenter submission for OS 6 will be open soon, so don't delay :)

**Comment by ianmjones** [comment]
Thanks @danrabbit. Just to be super clear, only Flatpaks are able to be reviewed now, and .debs will no longer be reviewed even if they are only intended for elementary OS 5?

**Comment by danrabbit** [comment]
@ianmjones yes that's correct. We'll no longer be publishing updates to deb packages

**Comment by ianmjones** [comment]
Thanks for confirming that @danrabbit.

Unfortunately Snippet Pixie is unable to be packaged as a Flatpak due to a core policy to block some of the accessibility dbus messages that Snippet Pixie needs. As such I might as well close this issue.

For anyone later finding this issue, please use the [Snap version of Snippet Pixie](https://snapcraft.io/snippetpixie) that works just fine on any Linux distribution that supports snaps.

There's also a [nixpkgs version](https://search.nixos.org/packages?query=snippetpixie) that I maintain, although I've not tested that version on anything but NixOS.

**Comment by danrabbit** [comment]
Hey @ianmjones I'm sorry to hear that! If you could do me a huge favor, could file an issue report against the [xdg desktop portal](https://github.com/flatpak/xdg-desktop-portal) regarding the kind of access snipping pixie needs? It would be good to start a conversation there so we can make sure apps like snippet pixie can be published as Flatpak in the future

**Comment by ianmjones** [comment]
Hey @danrabbit, I raised an issue on the flatpak repo a few months back as that's the level where the blocking happens.

https://github.com/flatpak/flatpak/issues/4365

There's been no response. :shrug:

**Comment by danrabbit** [comment]
Hey @ianmjones it would probably be helpful to raise the issue against portals instead. It's unlikely that the Flatpak sandbox will be relaxed, but instead it's more likely that we can add a supported API for the features you need in the form of a portal
